version: '3.5'
services:
  app:
    image: incent/php-5.6:mongo4
    #    build:
    #      context: ./
    #      dockerfile: ./docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "PHP_IDE_CONFIG=serverName=interview"
      - "XDEBUG_CONFIG=remote_host=192.168.1.99 remote_port=9000" # ?XDEBUG_SESSION_START=PHPSTORM
    networks:
      - interview

  web:
    build:
      context: ./docker
      dockerfile: ./web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./app/logs/nginx:/var/log/nginx
    ports:
      - 8080:80
      - 8443:443
    networks:
      interview:
        aliases:
          - abc.interview.test
          - allowed.interview.test
          - no-market.interview.test
          - market.interview.test
          - interview.test

  mysql:
    image: mysql:5.6.34
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=interview"
      - "MYSQL_USER=interview"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - 33061:3306
    networks:
      - interview

  redis:
    image: 'redis:3.0'
    ports:
      - 63791:6379
    networks:
      - interview

  mongo:
    image: 'mongo:4.0.4'
    ports:
      - 57017:27017
    volumes:
      - 'mongo-data:/data/db'
    networks:
      - interview

  memcached:
    image: 'memcached:1.5'
    networks:
      - interview

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - 8088:80
    volumes:
      - /sessions
    networks:
      - interview


volumes:
  mysql-data: {}
  mongo-data: {}

networks:
  interview:
    driver: bridge
    name: interview
