# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    auto_service:
       class: AppBundle\Service\AutoService
       arguments: ['@doctrine.orm.entity_manager']
